import { Metadata } from "next"

import Faq from "@/components/faq"
import Hero from "@/components/hero"
import Testimonials from "@/components/testimonials"
import Gallery from "@/components/gallery"

export const metadata: Metadata = {
  title: 'Criptokuz | ¡Gracias por aplicar!',
  description: 'Generated by create next app',
}

const ThankYouPage = () => {
  return (
    <>
      <main>
        <Hero
          isMain={false}
          title="Paso #1 (OBLIGATORIO)
          Mira el siguiente video para confirmar tu llamada"
          highlightWords={['Paso #1']}
          video='https://www.youtube.com/embed/dQw4w9WgXcQ?si=J6P-xiv3i1vIF9D5'
        />
        <Hero
          isMain={false}
          title="Paso #2 (OBLIGATORIO)
          Mira el entrenamiento de cómo convertirte en setter en 2023"
          highlightWords={['Paso #2']}
          video='https://www.youtube.com/embed/qOECE3AkOlQ?si=1ma39Jy4YcIn-e4G'
        />
        <Hero
          isMain={false}
          title='Paso #3 (OBLIGATORIO)
          Nuestro proceso para ser rentable en menos de 90 dias'
          video='https://www.youtube.com/embed/htvXBn3_kuA?si=VnyL3PR-sTFOHGC8'
          highlightWords={['Paso #3', 'rentable', '90 dias']}
        />
        <Testimonials
          isMain={false}
          title='Paso #4 (OBLIGATORIO)
          Mira nuestros casos de éxito de CriptoKuz'
          highlightWords={['Paso #4']}
        />
        <Faq />
        <Gallery
          isMain={false}
        />
      </main>
    </>
  )
}

export default ThankYouPage