import { Metadata } from "next"

import Faq from "@/components/faq"
import Hero from "@/components/hero"
import Testimonials from "@/components/testimonials"

export const metadata: Metadata = {
  title: 'Criptokuz | ¡Gracias por aplicar!',
  description: 'Generated by create next app',
}

const ThankYouPage = () => {
  return (
    <main
      className="container my-10"
    >
      <Hero
        isMain={false}
        title="¡Gracias por aplicar!"
        subtitle="Pronto nos pondremos en contacto contigo"
        highlightWords={['gracias']}
        video='https://www.youtube.com/embed/dQw4w9WgXcQ?si=J6P-xiv3i1vIF9D5'
      />
      <Testimonials />
      <Faq />
    </main>
  )
}

export default ThankYouPage