import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import MainNav from '@/components/main-nav'
import Footer from '@/components/footer'
import { ThemeProvider } from '@/providers/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Criptokuz',
  description: 'Generated by create next app',
  icons: ['/favicon.png']
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={`bg-gradient-to-br from-primary/40 to-30% ${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
        >
          <MainNav />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
